### ISSUE TITLE
Patch not working on Typeform, why not choose open source alternative?

### ISSUE THREAD

**Issue by jobenjada** [shawnCaza/compodio#1]
Hey Shawn!

I am writing to you because I found your issue with updating Typeform forms with a PATCH.

My name is Johannes, I am one of the co-founders of Formbricks (https://formbricks.com/)

We're building open-source form and survey infrastructure and will release our API this week. I'd love to hear more about what you have built with Typeform and how your developer experience has been.

We are looking for people exactly like you trying to tape custom code to Typeform. Many don't have the greatest experience and we would like to know what we should do right to get everyone building on top of Formbricks in the future.

If you have Discord we could chat there at https://formbricks.com/discord

Thanks a lot!
Johannes

**Comment by shawnCaza** [comment]
I just automated the process of taking content from Word to Typeform. Apart from the patch issue their API / Python SDK worked fine.
