### ISSUE TITLE
Use FeedLinks component instead of RssLink component on show pages

### ISSUE THREAD

**Issue by shawnCaza** [shawnCaza/compodio#19]
The shows page ([slug].tsx) should be updated to use the [FeedLinks](https://github.com/shawnCaza/compodio/blob/master/ui/components/show/podcastFeedLinks/feedLinks/FeedLinks.tsx) component instead of RssLink [on this line](https://github.com/shawnCaza/compodio/blob/master/ui/pages/shows/%5Bslug%5D.tsx#L91).

This will display any external feeds that _may_ be available for a show in addition to the internal compodio RSS feed. This component is already in use by the CardContent component.

**Comment by DanieII** [comment]
Hello! I want to contribute to the project but while I was configuring the development environment I got this error on the frontend: 

> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost/compodio/data//get_all_shows.php. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 500.

I know that's the api not letting the frontend access it but I don't know how to fix it.

**Comment by shawnCaza** [comment]
Thanks @DanieII  

If you're only working on the front end you should be able to use the following in .env.local without worrying about running the api locally, or having the images saved locally. That should make things a fair bit easier to get going: 

```
NEXT_PUBLIC_API_URI = 'https://api.compodio.com/'
NEXT_PUBLIC_feed_URI = 'https://api.compodio.com/feed/'
NEXT_PUBLIC_image_server_URI = 'https://images.compodio.com/'
```


I'm not certain why you're running into a CORS problem. If you really wanted to debug it, the access header is set to `*`or all [on line 5 here.](https://github.com/shawnCaza/compodio/blob/16d2a1c9413da7e42c489b69f066769aa6cefc32/data/get_all_shows.php#L5), Changing it to the following might help:

`header('Access-Control-Allow-Origin: *', true);`

Thanks for bringing this up. I'll have to update the the setup section of the readme to make setup easier for collaboration.
